### PR TITLE
Register form

### PR DESCRIPTION
**Pull request by t-bello7**
Contributes to #118

## What did you do?
Renders the register form with bootstrap.
## Why did you do it?
Gives a user-friendly interface to the register page.
## How have you tested it?
Yes.
## Were docs updated if needed?

- [x] No
- [ ] Yes
- [ ] N/A

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new console logs
- [x] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Comment by t-bello7** [comment]
@dmtrek14 Can you check this reference ?https://stackoverflow.com/questions/14141350/why-load-staticfiles-for-every-template-even-if-it-is-extended/14141707#14141707
It covers why you have to load the static files in all Django child templates.

**Comment by upkarlidder** [comment]
Thank you @t-bello7. I will wait for @dmtrek14 to review.

**Comment by dmtrek14** [comment]
@t-bello7 and @upkarlidder This looks good to me. I had asked the question about it in the other PR because I wasn't sure if it was necessary. Based on what @t-bello7 has found above, it seems that it is. Thanks for confirming, @t-bello7 .

**Comment by upkarlidder** [comment]
Thank you for clarifying. Leaving a screenshot here for future readers.

image

@dmtrek14, based on this discussion, the search page is broken. I actually checked out the main branch and I see it fails if I don't load bootstrap4 explicitly. @dmtrek14 can you please take a look? This also tells me we should at least add some sanity tests that request the main URLs including 
- `/search`
- `/locations`
- `/impacts`
- `/users/register`
- `/users/login`

I will create an issue on this.

**Comment by dmtrek14** [comment]
@upkarlidder I'm now seeing the same, which is odd since I think we'd both been able to see the search page okay before. I agree we need some additional sanity tests. I will take a look at things later today.

**Comment by upkarlidder** [comment]
> 

Thank you. Yes, I am confused that it worked before. Something changed, but I am not able to point a finger at it. I might look at the git logs to investigate later.

Also created #132

**Comment by upkarlidder** [comment]
@t-bello7 can we change the last two errors to say 
`Password field is required`
and
`Password confirmation field is required`.

@dmtrek14 thoughts?

It gives a little more context at the bottom of the page. You can add the commit back to your branch and it will show up in this PR.

**Comment by dmtrek14** [comment]
@upkarlidder I agree. If the error messages at the bottom are more specific, they will better help the user.

**Comment by upkarlidder** [comment]
@t-bello7 are you able to make this change? We are almost there!

**Comment by t-bello7** [comment]
Have not been able to make the changes. Can't seem to find how bootstrap rendres the error text

**Comment by dmtrek14** [comment]
@t-bello7 Check in the forms.py. That's where validation is happening on the inputs. You should be able to set a custom error message there in the function for the register form. Bootstrap is just showing whatever error message is being passed through from there. Does this sound right to you @upkarlidder?

**Comment by upkarlidder** [comment]
I agree with @dmtrek14. This is my take ...

The code is present in `users/views.py`. It uses the built in `UserCreationForm` form:

```
if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)
```

I sub classed this form in the same file and provide new error messages. This should live in `users/forms.py` and get imported here. I am just providing an example:
```
class RegisterUserForm(UserCreationForm):
  username = forms.CharField(required=True, max_length=30) 
  
  class Meta:
    model = User
    fields = ['username', 'password1', 'password2']

  def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].error_messages = {'required': 'Username field is required'}
        self.fields['password1'].error_messages = {'required': 'Password field is required'}
        self.fields['password2'].error_messages = {'required': 'Password confirmation field is required.'}

```

Then simply replace the built in usercreationform model with this new subclass
```
    if request.method != 'POST':
        # Display blank registration form.
        form = RegisterUserForm()
    else:
        # Process completed form.
        form = RegisterUserForm(data=request.POST)
```

image

**Comment by t-bello7** [comment]
Thank you at @dmtrek14  and @upkarlidder . You both are the best.

**Comment by upkarlidder** [comment]
@t-bello7 bumping again. Let us know if you need any help. Thanks!

**Pull request closed without merging**
