### PR TITLE
Add css to override Bootstrap colors for WCAG compliance

### LINKED ISSUE #117: Color contrast for some elements can be improved to meet WCAG 2.0 AA standards
### Background on the problem the feature will solve/improved user experience
The navigation links and 'primary' (Bootstrap's blue color) buttons do not have enough contrast between the background and foreground colors. Adding more contrast will bring these parts of the UI up to a11y standards.

Screenshots of navbar and buttons that don't currently meet WCAG contrast requirements:
home

menu
register
sign-in

update-profile

### Describe the solution you'd like

Updating some CSS to provide more contrast will ensure that folks with low vision or other visual impairments can see links and buttons.

### Tasks

[ ] The colors of either the background or the foreground will need to be adjusted in the css.
[ ] Manual testing of the contrast needs to be done (at the moment, there are no a11y unit tests). The aXe browser extension or the WebAIM Color Contrast checker are great tools for contrast

 
### Acceptance Criteria

The final colors should provide enough contrast between the in an element and the background so that text is clearly visible to those with any visual impairment (including color blindness).

### PR DESCRIPTION
**Pull request by dmtrek14**
Fixes #117 

## What did you do?
Added overrides for success, info, and primary buttons for Bootstrap, as well as color changes for the main menu
## Why did you do it?
In order to get color for buttons and navigation to meeting WCAG 2.0 AA guidelines for contrast
## How have you tested it?
I have run both the aXe extension, as well as WAVE and manually run the new color combinations through WebAIM's color contrast checker
## Were docs updated if needed?

- [ ] No
- [ ] Yes
- [X] N/A

#### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new console logs
- [X] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Comment by tonypearson** [comment]
The highlight boxes do not meet WebAIM contrast requirements.  Pick a different color.

WebAIM-2021-10-29 13-32-48

**Review by tonypearson — CHANGES_REQUESTED** [review]
The new "white" text provides 9.9:1 contrast, versus the 3.7:1 before, but now the new higlighting scheme square box elements provides only 1.7:1 not enough.

Example solution: choose a non-white color for text that is 4.5:1 contrast or better, and then let the highlight be just a full-white text.
WebAIM-2021-10-29 13-32-48

**Comment by dmtrek14** [comment]
Appreciate the review @tonypearson ! I'm going to change this up to simply add an outline around the link on hover/focus so that we can retain the nice, high contrast.
menu-hover
I'll push up in a few.

**Comment by upkarlidder** [comment]
Thank you @dmtrek14. I tested locally as well. LGTM as per our discussions with Tony.

Full screen:
image

Responsive mode:
image

**Review by tonypearson — APPROVED** [review]

**Pull request merged**
